CREATE TABLE STUDENT (
    SID INTEGER,
    NAME VARCHAR(128),
    EMAIL VARCHAR(128),
    PHONENO VARCHAR(128));

CREATE TABLE ENROLL (
    SID INTEGER,
    STARTDATE DATE,
    SNAME VARCHAR(128),
    TNO INTEGER,
    COUPON VARCHAR(128),
    AMOUNT INTEGER,
    TDATE DATE,
    CARDID VARCHAR(128),
    CARDENDDATE DATE,
    CARDTYPE VARCHAR(128));

CREATE TABLE TUTOR (
    TID INTEGER,
    STARTDATE DATE,
    SNAME VARCHAR(128),
    NAME VARCHAR(128),
    PHONENO VARCHAR(15),
    SUBSTITUTORID INTEGER);

CREATE TABLE ADMIN (
    AID INTEGER,
    CID INTEGER,
    NAME VARCHAR(128),
    PHONENO VARCHAR(15),
    EMAIL VARCHAR(128));

CREATE TABLE COURSE(
    CID INTEGER,
    SID INTEGER,
    CNAME VARCHAR(128));

CREATE TABLE SESSION(
    CID INTEGER,
    STARTDATE DATE,
    SNAME VARCHAR(128),
    SDESC VARCHAR(500),
    ENDDATE DATE,
    PRICE INTEGER);
